version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        - TaskDefinition: "arn:aws:ecs:ca-central-1:844403568518:task-definition/test:13"
        LoadBalancerInfo:
          - ContainerName: "test"
          ContainerPort: 80
